project_id = "dlsnflfqemavnhavtaxe"

[functions.send-invite]
verify_jwt = false

[functions.invite-manager]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.send-reminder]
verify_jwt = false